fieldLayouts:
  8384a32c-3ea9-4287-96f0-69443b18d770:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 666b232b-7cab-4912-b3df-62ac43b3d623
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1527f785-ba6f-4398-9ee1-b04be3fb7312 # Image
            instructions: null
            label: 'Immagine di anteprima'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f8a7c32-553b-4e3a-bac2-7f4c93abed07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e62e37ed-f85a-4cc0-a148-9e19a38136f3
            userCondition: null
            warning: null
            width: 100
        name: Contenuto
        uid: 1ec565b0-206e-4cee-b293-5d8ccefe1d16
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 321ea2f9-b424-4624-96b5-b9ff73a00a12 # SEO info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a7a8e67-7bd6-4200-8e33-a27357b9f8b6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 371f3f5b-a6f8-4292-9052-2c9c683506a2
        userCondition: null
handle: default
hasTitleField: true
name: 'Impostazione predefinita'
section: 3ffaf07c-d071-4499-b470-d79daa0c7aae # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
