fieldLayouts:
  b064c50e-ec2e-438d-b800-e5e0623615aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2b350efc-5fa7-4e60-93ec-3fdb1bcec977
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7751639b-9673-4569-912d-214b3c47ed13 # Nascondi il titolo della pagina
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95fb2b7c-a464-4329-b268-2b50573d0f75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1527f785-ba6f-4398-9ee1-b04be3fb7312 # Image
            instructions: null
            label: 'Immagine di anteprima'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23389f26-183a-42ce-9d99-eff335fb7ab5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f10396e-74cd-477f-80b7-f761b7788c7f
            userCondition: null
            warning: null
            width: 100
        name: Contenuto
        uid: cfef719a-7f4b-4102-8eb4-7970e2c000fd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15b3eff3-5121-4fef-9d89-f5e7cddbd372
            userCondition: null
            warning: null
            width: 100
        name: 'Preset colori'
        uid: 24b066ff-fca5-4fce-bb30-b381ec01056b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 321ea2f9-b424-4624-96b5-b9ff73a00a12 # SEO info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6494519c-4922-4999-8db3-d6971ef8d555
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bdc5c467-23e9-48b0-804c-3297033c768a
        userCondition: null
handle: default
hasTitleField: true
name: 'Impostazione predefinita'
section: 8819872b-fa81-4b02-9f91-1e6aa8cb1512 # Pagine
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
