defaultPlacement: end
fieldLayouts:
  92c6efc0-d79d-49ad-b14c-8bda0cea958e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 46580b2d-f7fd-441d-937f-52a5cd0d5f50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 9934932e-65e4-42f4-a895-fb7b34f360e5
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: c0b52fe7-a428-4ae9-a715-47d8d3cba6b4
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: c044a127-ebf3-445d-bda7-eb8196d735f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 13d14ec3-c6c7-4cd8-a4c3-fb89724b92c9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 9cf6a4e9-1ca5-4d92-bd02-31487f14d5e6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 5b12a4cb-59c0-4fed-bf01-fb48a29634bd
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 0354f231-63d8-4ca6-b494-0fa6797cd602
        userCondition: null
handle: menuOverlay
instructions: 'Questo menu è visibile solo da telefono'
maxNodes: null
name: 'Menu Overlay Mobile'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagateNodes: false
siteSettings:
  1c811c23-f7c4-4f7b-baee-bce5bb6e91dc: # Website EN
    enabled: true
  438f0b6e-6006-4026-93ab-4fffd2f8344c: # Website IT
    enabled: true
sortOrder: 4
structure:
  maxLevels: null
  uid: ad2b06b0-94c3-475a-b7ab-483c7662b382
