childBlocks:
  - blockTitleContent
  - blockTextContent
  - blockSpacer
  - blockImage
  - blockIcon
  - blockSeparator
  - blockVideo
  - blockButtons
  - blockCard
  - blockEmbed
  - blockGallery
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  2078acc4-4a98-4215-a426-15c96317cd38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24178ca3-7874-454a-884e-18edba9a37f4 # Nascondi da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bfad2a6-e051-45f9-8f6a-a5b1438359af
            userCondition: null
            warning: null
            width: 25
        name: Configurazioni
        uid: 2f534a6a-059c-4cae-9c12-d59add2e294b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1709740c-1551-458c-89cf-ab2153954e53
            userCondition: null
            warning: null
            width: 100
        name: 'Preset colori'
        uid: 5b3d622f-8a6f-466b-9112-3b8b3305c554
        userCondition: null
group: 3b36f1fb-0a72-4253-92dc-fbb743346705 # Campi Layout
handle: blockColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Column
sortOrder: 5
topLevel: false
