childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  49b3bbfc-4a61-48e6-8111-0f9a7797bcd6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c09af9fa-eafa-45b8-a5b9-b7efaad8f009 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6b189cb-ad5b-4e6f-9187-b4acd543bd86
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a524c41b-7dd0-4c3d-ad1d-080e9b06f106 # Larghezza immagine
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 501df5ad-9e56-453a-8d2c-eb455c335b99
            userCondition: null
            warning: null
            width: 25
        name: Contenuto
        uid: f56fc780-3aa4-4bcd-9dc7-fe51e178fbe8
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: blockIcon
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Icon
sortOrder: 13
topLevel: false
