childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  bf495540-f913-4f8d-8f4c-47a11177652a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24178ca3-7874-454a-884e-18edba9a37f4 # Nascondi da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606b3ac7-6f67-48fb-bea8-4cf11c92abf7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7ef3b99d-c202-4d05-8817-3ef44df87b9f # Allineamento Orizzontale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bfdfc2f-26c5-4c64-8b22-4d4e6173c589
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: bad8cf3d-1309-492c-b495-e2b21b37764f # Larghezza contenuto 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 151700af-81d8-4d3e-8110-d9d522eedc04
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 669b9615-8c6f-4b2f-a63b-d857368f0a12
            userCondition: null
          -
            elementCondition: null
            fieldUid: c09af9fa-eafa-45b8-a5b9-b7efaad8f009 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6214df1f-0e64-42f7-8f66-805bcfde861e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43d28f5a-3663-453a-8332-5fa3d0accc7a # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02743dae-a39d-495a-a643-fca51987f91e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf9dc95c-7aa1-45bb-ae8d-d7a7a53e8304 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 354f2647-a777-414f-8fa5-f7226dd9d162
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b706aa18-49d5-486f-8f47-3817e3cdedac # Text content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82114928-9e2e-4345-ae33-3a31ad5abbb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0867c770-0139-4bde-92e8-880080b164c8 # Pulsanti
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeb6f0ff-0d53-4b72-b1f2-e8e3babd14af
            userCondition: null
            warning: null
            width: 100
        name: Contenuto
        uid: 8294a3e3-0cb8-4d55-8df9-b4a4d6d5d92c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f41b439-cb99-4e0f-8149-758e632633a1 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b2528d4-b221-4fa8-bf6d-6ad23d4fe2cb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3b8a0247-0428-4d77-b26f-33fe4528d5ab # Colore del testo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 322526ae-9596-44c7-92fb-3924e1e1895f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: bb6a5f43-5774-4c2a-916b-74169652fd12 # Colore di background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c2a656d-df84-489e-97a3-265d5248e1e7
            userCondition: null
            warning: null
            width: 25
        name: Stile
        uid: 7cc9c104-9653-44dc-9828-89e398e5c362
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 127b06a8-73ce-4440-9d65-6e66434bd853
            userCondition: null
            warning: null
            width: 100
        name: 'Preset Colori'
        uid: f8b09fe5-da3b-4cd4-b3f9-3c8791cb5348
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: blockCard
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Card
sortOrder: 17
topLevel: false
