childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  412ea57b-d056-4107-99b6-a32ba0e8146b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 31a4ed37-b584-4751-b0b5-b3e53e0c5603 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1475fa7-1856-48b0-9a48-1a53d98d4a9e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0813e0c4-1715-4745-abf9-f0a5cef29bfc # Opzioni Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31094aba-4de7-4de2-a73e-54c361e63f43
            userCondition: null
            warning: null
            width: 50
        name: Contenuto
        uid: 28534855-1953-487c-9fd4-2189d0556126
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: blockVideo
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Video
sortOrder: 15
topLevel: false
