childBlocks:
  - blockColumn
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  f28fcfbd-1057-484d-921d-df5a2f269039:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24178ca3-7874-454a-884e-18edba9a37f4 # Nascondi da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec674461-bed8-4245-bd51-630a960c6232
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7ef3b99d-c202-4d05-8817-3ef44df87b9f # Allineamento Orizzontale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4042d0e7-d05b-4f02-be95-4a43dddd612c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a0c0ef16-7653-47fd-9061-ecdafe6d430f # Allineamento Verticale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a4b7980-ed80-4714-b5b4-288e70ab600e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: bad8cf3d-1309-492c-b495-e2b21b37764f # Larghezza contenuto 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d048e545-1c0d-4026-a09d-a17d1f1c3ecf
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 46650e46-01fe-4fb1-833e-8e1d99e48530 # Numero di colonne Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1218f20-f35f-409f-b62f-aee5e35cced0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ee8431b7-0df7-4e5a-92da-2aeb96d451bc # Numero di colonne Tablet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d3abc51-2282-47f2-8005-06a819002804
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b07de203-0c44-4603-bed6-e0cef2afcf90 # Numero di colonne Desktop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3bfa059-516a-4158-9fba-8ba329552acd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f2a1093d-aa07-407c-80ea-2b9379cb5779 # Numero di colonne Wide
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa6f0577-f64a-4201-adc0-7b9603edc5d2
            userCondition: null
            warning: null
            width: 25
        name: Configurazioni
        uid: fa86fb0b-24e5-4bfd-bbc6-c8adafba108e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb6a5f43-5774-4c2a-916b-74169652fd12 # Colore di background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d43e0997-ec3d-468b-96f6-408aad67d3d2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3b8a0247-0428-4d77-b26f-33fe4528d5ab # Colore del testo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54236f8e-d771-47a2-a653-d3ddedbf6c1d
            userCondition: null
            warning: null
            width: 25
        name: Stile
        uid: d78a3e31-2d85-4093-abdb-98e6affa5f29
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81b6ea15-02fd-419e-890d-494eccb7823d
            userCondition: null
            warning: null
            width: 100
        name: 'Preset Colori'
        uid: 54f6bdde-0de5-4a8e-b3ce-39491ecdf57f
        userCondition: null
group: 3b36f1fb-0a72-4253-92dc-fbb743346705 # Campi Layout
handle: blockColumns
maxBlocks: 0
maxChildBlocks: 6
maxSiblingBlocks: 0
name: Colonne
sortOrder: 4
topLevel: true
