childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  6585c28d-39f4-4ee3-8347-e2d1e9da5b72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ca808102-3dd3-4670-8725-29e67e3b7580 # Dimensione del testo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 716a7238-e689-4439-ac4f-9e5c0463f62b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3b8a0247-0428-4d77-b26f-33fe4528d5ab # Colore del testo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52b45044-b0ad-4d67-bb06-d78cc3325e52
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b706aa18-49d5-486f-8f47-3817e3cdedac # Text content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 646b2417-3fb3-4e0b-b83f-e671a07e7a35
            userCondition: null
            warning: null
            width: 100
        name: Contenuto
        uid: 3f995fac-dc14-4193-856b-52cf6d0d40df
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f41527a-ca2c-46ba-9653-85f98c2e4bce
            userCondition: null
            warning: null
            width: 100
        name: 'Preset Colori'
        uid: 00e761ab-4ed3-4e3d-87db-9db7cea53cee
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: fieldTextContent
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Text Content'
sortOrder: 10
topLevel: false
