childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  81191222-0d73-4def-b830-8bc9fa4da8f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d816f8a-85a4-42a4-873d-091a271a7505 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76dc21d7-bbf8-48cb-a1fc-eafa993f2fdc
            userCondition: null
            warning: null
            width: 100
        name: Contenuto
        uid: 778c3131-2e1d-4dfd-a3a9-6ee327b95cf2
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: fieldLink
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Link
sortOrder: 16
topLevel: false
