childBlocks: null
description: ''
field: c3be3a6e-94d3-47a6-a914-53bfffed5d81 # Content Manager
fieldLayouts:
  79c9a11f-2f65-4167-ae35-ebd9168b45c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73ff6059-2d8b-4a04-96fe-50b137bf79cf # Separator
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d71eeabc-4e5e-4b4f-a822-3d8851bcad0e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bb6a5f43-5774-4c2a-916b-74169652fd12 # Colore di background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 673962d9-0dd5-43cb-98f5-6282ff473ae5
            userCondition: null
            warning: null
            width: 50
        name: Contenuto
        uid: a6f0749b-f3ea-4357-bf44-b8587351b995
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6677968f-f800-4f1b-b442-9eb3030ec503 # Preset colori
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5f7a5cf-02c5-4c8a-93d5-cd0ac0ad9c42
            userCondition: null
            warning: null
            width: 100
        name: 'Preset Colori'
        uid: d5ba7701-99ee-412e-b1b0-c3c05d50f375
        userCondition: null
group: 6b0a27c7-23fd-4d8f-a780-551ac5a52981 # Campi Base
handle: fieldSeparator
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Separator
sortOrder: 14
topLevel: false
