childBlocks: null
description: ''
field: 1243147e-fe16-4f7b-b259-3fc728ef1ba3 # Social
fieldLayouts:
  3a7f0a46-ee6c-42c1-bf8a-ce56614ff12e:
    tabs:
      -
        elements:
          -
            fieldUid: 6d816f8a-85a4-42a4-873d-091a271a7505 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae2b7d72-2ca7-4590-af69-e28c5c55ba33
            warning: null
            width: 100
        name: Youtube
        uid: e41faa1b-59ce-412c-8e16-5146232dd502
group: null
handle: youtube
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 1
name: Youtube
sortOrder: 5
topLevel: true
