isPublic: false
name: 'Schema preview'
scope:
  - 'sites.438f0b6e-6006-4026-93ab-4fffd2f8344c:read' # Website IT
  - 'sites.1c811c23-f7c4-4f7b-baee-bce5bb6e91dc:read' # Website EN
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.1883fea6-975a-407a-8d63-9f8c99aa2f12:read' # Archivio News
  - 'entrytypes.e6e06e73-bee4-4ebf-a8bb-407ea9db43de:read' # Archivio News
  - 'sections.7ed99a8c-d1da-4403-8fe6-d7970a591477:read' # Home Page
  - 'entrytypes.c22ba1ab-6375-49cc-a1c3-34a58fe41879:read' # Home Page
  - 'sections.3ffaf07c-d071-4499-b470-d79daa0c7aae:read' # News
  - 'entrytypes.e92ae8db-5365-498b-9314-9befd8d4f05c:read' # Impostazione predefinita
  - 'sections.8819872b-fa81-4b02-9f91-1e6aa8cb1512:read' # Pagine
  - 'entrytypes.129ace49-4a04-4d35-bf8d-ddad2809e478:read' # Impostazione predefinita
  - 'volumes.a55ddf83-f714-4721-b32b-67b02cf59ef6:read' # Media
  - 'volumes.ca924c9a-2a3b-4659-8159-8c68eb20d053:read' # Avatars
  - 'globalsets.7dcd5dd4-f91a-4a3d-b45e-26f2c9d57885:read' # Informazioni SEO
  - 'globalsets.5b131fca-5cfb-4f35-bb4c-9b467d658386:read' # Socials
  - 'globalsets.c97d6f1a-2cbc-449b-81d6-215aafe99f6c:read' # Footer 1
  - 'globalsets.f9d91014-3ce9-4bf6-9ff8-e6e2a5ee3627:read' # Footer 2
  - 'globalsets.d6bdd481-7959-416a-a3ed-dec453773a89:read' # Footer 3
  - 'globalsets.6ed7b8ac-4d2d-48fc-bf49-e63fb9703ecf:read' # Footer 4
  - 'navigationNavs.all:read'
  - 'navigationNavs.2adb9439-35bf-472c-ae48-a844bf8f5af3:read' # Menu Main Desktop
  - 'navigationNavs.ee8b0c18-3c9d-4842-b80f-bf1819717122:read' # Menu Overlay Mobile
