columnSuffix: vyjaxjse
contentColumnType: string
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: alignment
instructions: null
name: 'Allineamento Orizzontale'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Sinistra
        -
          - value
          - horizontal-left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Centrato
        -
          - value
          - horizontal-center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Destra
        -
          - value
          - horizontal-right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\RadioButtons
