columnSuffix: kxqxskmw
contentColumnType: string
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: columnNumberDesktop
instructions: null
name: 'Numero di colonne Desktop'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1 Colonna'
        -
          - value
          - desktop-grid-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2 Colonne'
        -
          - value
          - desktop-grid-2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3 Colonne'
        -
          - value
          - desktop-grid-3
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4 Colonne'
        -
          - value
          - desktop-grid-4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - desktop-grid-auto
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
