columnSuffix: fcvzxrnw
contentColumnType: string
fieldGroup: 72716926-fc36-4d07-a273-2c29a2eb8287 # Campi aggiuntivi
handle: fieldListFilter
instructions: null
name: 'Filtro contenuto'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Vedi tutti'
        -
          - value
          - seeAll
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Selezione
        -
          - value
          - selection
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\RadioButtons
