columnSuffix: stqazxzv
contentColumnType: string(255)
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldEmail
instructions: null
name: Email
searchable: false
settings:
  maxLength: 255
  types:
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
