columnSuffix: null
contentColumnType: string
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldButtons
instructions: null
name: Pulsanti
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 2044950698
  columns:
    __assoc__:
      -
        - 47c53f3a-0468-4e00-b88a-ff437368d140 # Pulsante
        -
          __assoc__:
            -
              - width
              - ''
      -
        - a7938778-e7ae-4ecb-9f18-c4832f1f0703 # Stile del bottone
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_fieldbuttons}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add new button'
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
