columnSuffix: gmxcysjj
contentColumnType: text
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldNavigationMenu
instructions: null
name: 'Navigation menu'
searchable: false
translationKeyFormat: null
translationMethod: site
type: verbb\navigation\fields\NavigationField
