columnSuffix: ybwtuqxd
contentColumnType: string
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldSpacerMobile
instructions: null
name: 'Spacer Mobile'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Very Small 10px'
        -
          - value
          - space-verysmall-mobile
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Small 35px'
        -
          - value
          - space-small-mobile
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Medium 60px'
        -
          - value
          - space-medium-mobile
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Large 75px'
        -
          - value
          - space-large-mobile
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Very Large 100px'
        -
          - value
          - space-verylarge-mobile
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
