columnSuffix: mrfyqdsh
contentColumnType: string(255)
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldUrl
instructions: null
name: Url
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
