columnSuffix: null
contentColumnType: text
fieldGroup: 852db3e5-fe6a-4193-a94e-9fc2f6138ccc # Campi di base
handle: fieldEmbed
instructions: 'Inserisci l''embed'
name: Embed
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
