columnSuffix: njnmnjwo
contentColumnType: integer(10)
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: imageWidth
instructions: 'Dimensioni in px'
name: 'Larghezza immagine'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Number
