columnSuffix: tsymzxpn
contentColumnType: string
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: optionOrientation
instructions: null
name: 'Orientamento degli elementi'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Orizzontali
        -
          - value
          - horizontal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Verticali
        -
          - value
          - vertical
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\RadioButtons
