columnSuffix: ljajttxm
contentColumnType: string
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: optionFontSize
instructions: null
name: 'Dimensione del testo'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Testo 14/18 - 14/18'
        -
          - value
          - size-text-sm
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Testo 16/24 - 16/24'
        -
          - value
          - size-text-base
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Testo 18/24 - 18/24'
        -
          - value
          - size-text-mlg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Testo 24/24 - 24/24'
        -
          - value
          - size-text-lg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Testo 32/36 - 32/36'
        -
          - value
          - size-text-xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Testo 48/48 - 32/32'
        -
          - value
          - size-text-2xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Testo 90/90 - 48/48'
        -
          - value
          - size-text-3xl
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
