columnSuffix: aayxelqb
contentColumnType: boolean
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: optionMarginTop
instructions: null
name: 'Aggiungere spaziatura dall''alto'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
