columnSuffix: null
contentColumnType: string
fieldGroup: 72716926-fc36-4d07-a273-2c29a2eb8287 # Campi aggiuntivi
handle: selectNews
instructions: null
name: 'Scelta News'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  source: null
  sources:
    - 'section:3ffaf07c-d071-4499-b470-d79daa0c7aae' # News
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
