columnSuffix: ackxmfni
contentColumnType: text
fieldGroup: afaa687b-ea74-450d-ae0a-dce52fbd66fa # Layout
handle: seoInfo
instructions: null
name: 'SEO info'
searchable: false
settings:
  description: ''
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage: ''
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title}'
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - ' - {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: site
type: ether\seo\fields\SeoField
