columnSuffix: null
contentColumnType: string
fieldGroup: ecf723b4-42fb-42b8-8e7e-ba1f8119c684 # Globali
handle: social
instructions: null
name: Social
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
