columnSuffix: uzqomqgp
contentColumnType: string
fieldGroup: cc5cc4b1-3070-415f-a2e3-921644b96e01 # Campi opzione
handle: videoSettings
instructions: 'L''autoplay funziona solo se il video è impostato come muted'
name: 'Opzioni Video'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Muted
        -
          - value
          - muted
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Controls
        -
          - value
          - controls
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Autoplay
        -
          - value
          - autoplay
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Loop
        -
          - value
          - loop
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Checkboxes
