dateModified: 1663313533
elementSources:
  craft\elements\Entry:
    -
      disabled: true
      key: '*'
      tableAttributes:
        - author
        - link
      type: native
    -
      disabled: false
      key: singles
      tableAttributes:
        - section
        - type
      type: native
    -
      heading: Strutture
      type: heading
    -
      key: 'section:3ffaf07c-d071-4499-b470-d79daa0c7aae' # News
      type: native
    -
      disabled: false
      key: 'section:8819872b-fa81-4b02-9f91-1e6aa8cb1512' # Pagine
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
email:
  fromEmail: $EMAIL_GENERAL_ADDRESS
  fromName: $EMAIL_GENERAL_NAME
  replyToEmail: $EMAIL_REPLYTO_ADDRESS
  template: ''
  transportSettings:
    encryptionMethod: $SMTP_ENCRYPTION_METHOD
    host: $SMTP_HOSTNAME
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  avatar:
    hasUrls: true
    name: Avatar
    settings:
      path: '@webRootFileSystem/avatar'
    type: craft\fs\Local
    url: '@webFileSystem/avatar'
  media:
    hasUrls: true
    name: Media
    settings:
      path: '@webRootFileSystem/media'
    type: craft\fs\Local
    url: '@webFileSystem/media'
meta:
  __names__:
    0e03688e-0017-40dc-9ebb-eaa72b8dc169: Table # Table
    1bc03632-e40f-4da1-bff8-78d3385735a4: Title # Title
    1c811c23-f7c4-4f7b-baee-bce5bb6e91dc: 'Website EN' # Website EN
    1ebc4402-0ecd-49b3-9322-f571be50d5da: 'Campi PIM' # Campi PIM
    1ec6ae18-7bff-4a14-abd0-9d855e25aa43: 'Text Content' # Text Content
    1edbf544-ebca-4202-af44-efbe142a4935: BC_id # BC_id
    2a2d70ff-f85a-44a0-bcf6-f11e1a12f10f: 'Coordinate X' # Coordinate X
    2adb9439-35bf-472c-ae48-a844bf8f5af3: 'Menu Main Desktop' # Menu Main Desktop
    2d824edd-0d3c-4077-bb56-71714bbee540: 'Colore del testo' # Colore del testo
    3b8a0247-0428-4d77-b26f-33fe4528d5ab: 'Colore del testo' # Colore del testo
    3b8d4c9e-5d35-4fcb-a6e6-177a8c5b8342: 'Navigation menu' # Navigation menu
    3b36f1fb-0a72-4253-92dc-fbb743346705: 'Campi Layout' # Campi Layout
    3bef3075-cca8-43a2-a22b-b19698be9c3c: Spacer # Spacer
    3ffaf07c-d071-4499-b470-d79daa0c7aae: News # News
    4a855ef9-41cf-4db0-9e81-db178418a24c: Card # Card
    5b131fca-5cfb-4f35-bb4c-9b467d658386: Socials # Socials
    5f4ff68c-c307-4f24-9064-0ff8e0ed2724: 'Campi Relazione' # Campi Relazione
    6b0a27c7-23fd-4d8f-a780-551ac5a52981: 'Campi Base' # Campi Base
    6d816f8a-85a4-42a4-873d-091a271a7505: Link # Link
    6d218754-d43c-4fa0-924c-1619ebdf5410: 'Contenuto Testuale' # Contenuto Testuale
    6ed7b8ac-4d2d-48fc-bf49-e63fb9703ecf: 'Footer 4' # Footer 4
    6f41b439-cb99-4e0f-8149-758e632633a1: 'Background Image' # Background Image
    7dcd5dd4-f91a-4a3d-b45e-26f2c9d57885: 'Informazioni SEO' # Informazioni SEO
    07e415ff-0821-4631-88ba-2e370ee61018: 'Orientamento degli elementi' # Orientamento degli elementi
    7ed99a8c-d1da-4403-8fe6-d7970a591477: 'Home Page' # Home Page
    7ef3b99d-c202-4d05-8817-3ef44df87b9f: 'Allineamento Orizzontale' # Allineamento Orizzontale
    08c96971-ae40-49f6-bcb3-285abbf0a86e: 'Campi relazionali' # Campi relazionali
    8e18f6d0-0fd3-4383-b457-6e7450d2fd58: Facebook # Facebook
    9f02621a-3aa7-4964-9432-3c2a12ebb8e4: Spacer # Spacer
    15db7523-77fd-4128-95ec-2466cb17ecd0: 'Schema preview' # Schema preview
    19ae9f94-9a82-4fa9-a474-501a0ec6c885: 'Menu di navigazione' # Menu di navigazione
    31a4ed37-b584-4751-b0b5-b3e53e0c5603: Video # Video
    34e710f6-90da-4fba-bc98-c2cc88ee496b: text # text
    38bcd39a-ff3b-4a78-ad56-6f3cc642fe2c: Default # Default
    39d9e3f3-e548-425d-abec-8c10a3bc61db: 'Coordinate Y' # Coordinate Y
    43d28f5a-3663-453a-8332-5fa3d0accc7a: Title # Title
    47c53f3a-0468-4e00-b88a-ff437368d140: Pulsanti # Pulsanti
    48f00871-2b8f-4bfd-ad93-a2079acfb94f: Editor # Editor
    48fcdb58-2ba1-4a7b-8c49-ccbe35612cd9: Embed # Embed
    52dc4d15-d7aa-473c-83ac-137ddfd8ef97: relation # relation
    62c5ae27-e4fa-403f-bbb7-60885b89c3ea: 'Rendere visibile solo agli utenti loggati?' # Rendere visibile solo agli utenti loggati?
    068aaab7-485d-48fa-8ecc-8ddddb257a15: 'Visualizza come slider' # Visualizza come slider
    73ebb5e2-3463-4b24-84cd-3766b8e0e524: 'Scelta News' # Scelta News
    73ff6059-2d8b-4a04-96fe-50b137bf79cf: Separator # Separator
    82b8a653-5847-4900-8b2a-7a04ff30ce8a: Colonne # Colonne
    88f23f1e-6e96-467c-80ae-5735c97649c1: 'Menu di navigazione' # Menu di navigazione
    94e77adc-35f1-476d-9ad7-b5b79cb6275c: relation # relation
    129ace49-4a04-4d35-bf8d-ddad2809e478: 'Impostazione predefinita' # Impostazione predefinita
    310ab773-172d-4dda-9530-fbcf4fdafd9b: Buttons # Buttons
    321ea2f9-b424-4624-96b5-b9ff73a00a12: 'SEO info' # SEO info
    0336f2f0-e28d-445a-9c61-d7c55691bdf4: 'Spacer Mobile' # Spacer Mobile
    438f0b6e-6006-4026-93ab-4fffd2f8344c: 'Website IT' # Website IT
    568b030e-c6e9-4f23-aa43-b6dfd97b2914: 'Campo condizionale' # Campo condizionale
    570b9270-9f25-4825-a429-3e0e67cc0b15: Bottone # Bottone
    0813e0c4-1715-4745-abf9-f0a5cef29bfc: 'Opzioni Video' # Opzioni Video
    829baeae-f431-41d7-a2d2-02453e722302: 'Contenuto Testuale' # Contenuto Testuale
    852db3e5-fe6a-4193-a94e-9fc2f6138ccc: 'Campi di base' # Campi di base
    0867c770-0139-4bde-92e8-880080b164c8: Pulsanti # Pulsanti
    971c7eeb-1940-4687-894e-97a31451a0d8: 'Background Video' # Background Video
    1527f785-ba6f-4398-9ee1-b04be3fb7312: Image # Image
    1883fea6-975a-407a-8d63-9f8c99aa2f12: 'Archivio News' # Archivio News
    2364a473-6b46-46fb-b17e-ab06a4730a22: 'Colore del bordo' # Colore del bordo
    3897ffaf-6798-4001-9434-d0ca315e1721: LinkedIn # LinkedIn
    7630eb7a-a6fb-42a8-ab0a-803e16bfc054: 'Filtro contenuto' # Filtro contenuto
    8093c2ae-1031-46be-ae92-e2cea6b63712: 'Contenuto Testuale' # Contenuto Testuale
    24178ca3-7874-454a-884e-18edba9a37f4: 'Nascondi da' # Nascondi da
    27966bfd-ae9e-41c7-b5a1-30f85515eb67: 'Contenuto Testo' # Contenuto Testo
    46650e46-01fe-4fb1-833e-8e1d99e48530: 'Numero di colonne Mobile' # Numero di colonne Mobile
    58214e02-1bee-4655-8760-28aaa4ebbd27: Embed # Embed
    68216db3-2750-491c-bddc-06157fb991fe: 'Categoria news' # Categoria news
    410016ad-5715-4c4b-b877-d5cf1d04dcb0: 'Lista News' # Lista News
    962110f8-a6a9-427d-b9b4-096961d93314: 'Plain Title' # Plain Title
    987296f1-ee9e-4410-9918-1dac409cef28: Hero # Hero
    1243147e-fe16-4f7b-b259-3fc728ef1ba3: Social # Social
    1555359d-05dc-46b0-9cd3-bd9b19ab6e2a: Image # Image
    01871172-6067-4101-9b6d-1d26bedc93d7: 'Public Schema' # Public Schema
    02428605-d765-4d61-bd92-4d96b28abc53: Base # Base
    6677968f-f800-4f1b-b442-9eb3030ec503: 'Preset colori' # Preset colori
    6818704a-9d3f-4fb5-a26a-63c59babd161: Images # Images
    07473540-e06e-4000-a0d3-f7a4723b4ad9: 'Plain Description' # Plain Description
    7751639b-9673-4569-912d-214b3c47ed13: 'Nascondi il titolo della pagina' # Nascondi il titolo della pagina
    8819872b-fa81-4b02-9f91-1e6aa8cb1512: Pagine # Pagine
    72716926-fc36-4d07-a273-2c29a2eb8287: 'Campi aggiuntivi' # Campi aggiuntivi
    a0c0ef16-7653-47fd-9061-ecdafe6d430f: 'Allineamento Verticale' # Allineamento Verticale
    a0ca8d47-ea2e-4c7c-bda9-6a9ee5c55a3c: Video # Video
    a1b33862-dec4-4567-9059-d12eb449fd6c: 'Stile del bottone' # Stile del bottone
    a55ddf83-f714-4721-b32b-67b02cf59ef6: Media # Media
    a524c41b-7dd0-4c3d-ad1d-080e9b06f106: 'Larghezza immagine' # Larghezza immagine
    a7938778-e7ae-4ecb-9f18-c4832f1f0703: 'Stile del bottone' # Stile del bottone
    ab91f4c0-45cc-496c-bf2c-9ca6dcd09a78: relation # relation
    ab1131d2-82b5-4517-b18b-71e6dd6d91e0: Column # Column
    afaa687b-ea74-450d-ae0a-dce52fbd66fa: Layout # Layout
    b027cae0-2a88-451d-a2a5-8a8a4b122dfb: Gallery # Gallery
    b07de203-0c44-4603-bed6-e0cef2afcf90: 'Numero di colonne Desktop' # Numero di colonne Desktop
    b3a899f2-adc6-442d-927d-45aede27e55f: 'Contenuto footer' # Contenuto footer
    b81fb740-8603-4776-98c0-7db7187d226a: 'Layout 2' # Layout 2
    b706aa18-49d5-486f-8f47-3817e3cdedac: 'Text content' # Text content
    b836990b-eb32-4e70-8a19-6ece85ed0918: Gruppo # Gruppo
    bad8cf3d-1309-492c-b495-e2b21b37764f: 'Larghezza contenuto ' # Larghezza contenuto 
    bb6a5f43-5774-4c2a-916b-74169652fd12: 'Colore di background' # Colore di background
    c09af9fa-eafa-45b8-a5b9-b7efaad8f009: Icon # Icon
    c3be3a6e-94d3-47a6-a914-53bfffed5d81: 'Content Manager' # Content Manager
    c22ba1ab-6375-49cc-a1c3-34a58fe41879: 'Home Page' # Home Page
    c97d6f1a-2cbc-449b-81d6-215aafe99f6c: 'Footer 1' # Footer 1
    c135abde-0e56-47f4-a862-f21493c626cf: 'Numero di elementi' # Numero di elementi
    c324b3de-7eb4-4942-9ca3-241f370efd2b: 'Colore di sfondo' # Colore di sfondo
    c802962d-85e4-4c35-b79f-4c28fca1cbbd: Instagram # Instagram
    ca4f0220-128a-4382-b21d-35fabd9d01bf: Pulsante # Pulsante
    ca924c9a-2a3b-4659-8159-8c68eb20d053: Avatars # Avatars
    ca18661f-a8e8-4c06-b811-c6fc8db76240: 'Menu di navigazione' # Menu di navigazione
    ca808102-3dd3-4670-8725-29e67e3b7580: 'Dimensione del testo' # Dimensione del testo
    cc5cc4b1-3070-415f-a2e3-921644b96e01: 'Campi opzione' # Campi opzione
    cc8e1a65-d41e-4ca3-af8f-57e8c2952205: 'Text Content' # Text Content
    cc486f22-b69a-4922-92c9-5864514c7296: Contenuto # Contenuto
    cf9dc95c-7aa1-45bb-ae8d-d7a7a53e8304: Subtitle # Subtitle
    d2b07453-2e8c-4f8c-a955-3528d641401e: Twitter # Twitter
    d6bdd481-7959-416a-a3ed-dec453773a89: 'Footer 3' # Footer 3
    d75477dc-f48e-489a-aed7-3dbbe6e10524: Icon # Icon
    e6cfad4d-76fb-4e01-9a67-7709b209f909: Youtube # Youtube
    e6e06e73-bee4-4ebf-a8bb-407ea9db43de: 'Archivio News' # Archivio News
    e38e1156-783e-4883-ac45-3ebe22c10c44: Separator # Separator
    e79af673-6780-4a1f-b1a3-d277938bc5cd: 'Image 1' # Image 1
    e92ae8db-5365-498b-9314-9befd8d4f05c: 'Impostazione predefinita' # Impostazione predefinita
    e62447fb-c123-45fb-8e62-05cdeb9bc64d: Layout # Layout
    ecf723b4-42fb-42b8-8e7e-ba1f8119c684: Globali # Globali
    ee8b0c18-3c9d-4842-b80f-bf1819717122: 'Menu Overlay Mobile' # Menu Overlay Mobile
    ee8431b7-0df7-4e5a-92da-2aeb96d451bc: 'Numero di colonne Tablet' # Numero di colonne Tablet
    f2a61bce-0871-45dc-bdb0-d9b856ebc7e3: image # image
    f2a1093d-aa07-407c-80ea-2b9379cb5779: 'Numero di colonne Wide' # Numero di colonne Wide
    f5bca9ff-effe-471d-99cf-ade304c4ccd2: 'Altezza del blocco' # Altezza del blocco
    f8c4f6f4-b454-46d2-91f4-1c88657d8572: 'Campi avanzati' # Campi avanzati
    f9d91014-3ce9-4bf6-9ff8-e6e2a5ee3627: 'Footer 2' # Footer 2
    f8906e57-e779-4d8b-a2f1-b6b17681d801: Link # Link
    fb128c7a-34fe-4612-ad53-f2b1174f16c0: 'Background Video Mobile' # Background Video Mobile
    fee9285c-623a-4f9d-af07-fcff5787c163: Vimeo # Vimeo
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  craft-deploy-trigger:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: SXV4YFGO4N4CTTXKKVJD2N1O
    schemaVersion: 2.0.2
    settings:
      bypassProjectConfig: false
      pluginName: Menu
  neo:
    edition: standard
    enabled: true
    licenseKey: DIP2SMWHEOUIMUNZKNCJL76S
    schemaVersion: 3.0.4
  readonly:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - wsb
            -
              - locked
              - '1'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - kz5
            -
              - locked
              - '0'
            -
              - template
              - '{{ - Fast Spa }}'
      titleSuffix: null
      twitterHandle: ''
  simplemap:
    edition: lite
    enabled: false
    schemaVersion: 3.4.2
    settings:
      apiKey: null
      browserApiKey: null
      disablePopulateMissingFieldData: false
      geoLocationAutoRedirect: false
      geoLocationCacheDuration: 5270400
      geoLocationService: none
      geoLocationToken: ''
      geoService: nominatim
      geoToken: ''
      mapTiles: carto.light_all
      mapToken: ''
      serverApiKey: null
      unrestrictedApiKey: null
      w3wEnabled: false
      w3wToken: ''
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: $SYSTEM_TIMEZONE
