field: 0867c770-0139-4bde-92e8-880080b164c8 # Pulsanti
fieldLayouts:
  79163621-72f8-472f-ad1b-5d5f5c97eb27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 47c53f3a-0468-4e00-b88a-ff437368d140 # Pulsanti
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15a04dd5-aa2b-4771-a1db-47b469665284
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7938778-e7ae-4ecb-9f18-c4832f1f0703 # Stile del bottone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9558aaa3-fea5-45a3-a94b-ffe73f38bd65
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77de323f-e26c-463e-884d-fede77f66de6
        userCondition: null
fields:
  47c53f3a-0468-4e00-b88a-ff437368d140: # Pulsanti
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: null
    name: Pulsanti
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  a7938778-e7ae-4ecb-9f18-c4832f1f0703: # Stile del bottone
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: null
    name: 'Stile del bottone'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Nero pieno'
            -
              - value
              - fullBlack
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bianco pieno'
            -
              - value
              - fullWhite
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Nero bordato'
            -
              - value
              - borderedBlack
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bianco bordato'
            -
              - value
              - borderedWhite
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\RadioButtons
