field: 0867c770-0139-4bde-92e8-880080b164c8 # Pulsanti
fieldLayouts:
  79163621-72f8-472f-ad1b-5d5f5c97eb27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 47c53f3a-0468-4e00-b88a-ff437368d140 # Pulsante
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ba50f53-f8cb-4881-a069-18178566b2ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7938778-e7ae-4ecb-9f18-c4832f1f0703 # Stile del bottone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0482591f-e183-41f7-85d8-59b344b66857
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77de323f-e26c-463e-884d-fede77f66de6
        userCondition: null
fields:
  47c53f3a-0468-4e00-b88a-ff437368d140: # Pulsante
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldButton
    instructions: null
    name: Pulsante
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  a7938778-e7ae-4ecb-9f18-c4832f1f0703: # Stile del bottone
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldButtonStyle
    instructions: null
    name: 'Stile del bottone'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Standard
            -
              - value
              - standard
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - invertito
            -
              - value
              - inverse
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\RadioButtons
