fieldLayouts:
  b61ae713-1f6f-4222-abe3-a1fc650dc622:
    tabs:
      -
        elements:
          -
            fieldUid: b3a899f2-adc6-442d-927d-45aede27e55f # Contenuto footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fecde8e-be9a-4df9-b401-3b108127daa0
            warning: null
            width: 100
        name: 'Contenuto Footer 3'
        uid: 2a07d25c-ff22-439b-a1fe-dfd3f17517a9
handle: footer3
name: 'Footer 3'
sortOrder: 6
