defaultPlacement: end
enableVersioning: true
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Pagina articolo primaria'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  438f0b6e-6006-4026-93ab-4fffd2f8344c: # Website IT
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'news/{slug}'
type: channel
