defaultPlacement: end
enableVersioning: true
handle: newsArchive
name: 'Archivio News'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Pagina articolo primaria'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1c811c23-f7c4-4f7b-baee-bce5bb6e91dc: # Website EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: news
  438f0b6e-6006-4026-93ab-4fffd2f8344c: # Website IT
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: news
type: single
